Initial code.
kubewarden/psa-label-enforcer-policy pull request #1
Opened 2023-05-17 15:24 UTC by jvanz

## Description

Initial code implementing the policy to enforce PSA labels in the namespaces deployed in the cluster.

Fix https://github.com/kubewarden/kubewarden-controller/issues/451

2023-05-18 13:14 UTC, flavio requested changes
LGTM, I left some minor notes

2023-05-18 14:18 UTC, jvanz commented on src/settings.rs
> +    fn validate(&self) -> Result<(), String> {
No reason. It just the current implementation from the [template](https://github.com/kubewarden/rust-policy-template/blob/01173695123c7bbb358f11287c328f996f621317/src/settings.rs#L13)

2023-05-22 13:35 UTC, jvanz commented
@jordojordo can you review the questions file that I just added in the PR?

2023-05-22 13:39 UTC, jordojordo commented
@jvanz The `questions-ui.yml` looks good! The `artifacthub-pkg.yml` should be good to update with those questions now.

2023-05-22 13:56 UTC, flavio requested changes

2023-05-22 13:56 UTC, flavio commented on Cargo.toml
> +slog = "2.7"
I think this can be removed now

2023-05-22 14:40 UTC, jvanz commented
@flavio I'm merging this PR because I've removed the `slog` dependency.

2023-05-22 14:41 UTC, merged